### ISSUE TITLE
Crashes AS AF Beta 2 on open (Linux)

### ISSUE THREAD

**Issue by sindrenm** [c5inco/Compose-Modifiers-Playground#3]
When opening the Playground in Android Studio Arctic Fox Beta 2, I see a black window for a short time and then Studio crashes with the following message:

```
Shader compilation error
------------------------
   1	noperspective in float4 vinCircleEdge_Stage0;noperspective in half4 vinColor_Stage0;out half4 sk_FragColor;
   2	void main() {half4 outputColor_Stage0;half4 outputCoverage_Stage0;{ // Stage 0, CircleGeometryProcessor
   3	float4 circleEdge;circleEdge = vinCircleEdge_Stage0;outputColor_Stage0 = vinColor_Stage0;float d = length(circleEdge.xy);half distanceToOuterEdge = half(circleEdge.z * (1.0 - d));half edgeAlpha = saturate(distanceToOuterEdge);outputCoverage_Stage0 = half4(edgeAlpha);}{ // Xfer Processor: Porter Duff
   4	sk_FragColor = outputColor_Stage0 * outputCoverage_Stage0;}}
Errors:
error: 3: floating-point value is too large: 1.0
1 error

free(): invalid pointer
Aborted (core dumped)
```

I'm on Linux, but figured that since there's no system requirements mentioned in the README, this should be fine.

Some Studio/system information:

```
Android Studio Arctic Fox | 2020.3.1 Beta 2
Build #AI-203.7717.56.2031.7375522, built on May 19, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.0-7614-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry: ide.instant.shutdown=false, external.system.auto.import.disabled=true
Non-Bundled Plugins: com.c5inco.modifiers, io.kanro.idea.plugin.protobuf, org.toml.lang, org.jetbrains.kotlin, com.developerphil.adbidea, org.jetbrains.compose.desktop.ide, com.nbadal.ktlint, org.intellij.plugins.markdown
Current Desktop: pop:GNOME
```

**Comment by c5inco** [comment]
Thanks for the report! That's very interesting since my plugin code itself is not touching shaders or native code at all. Are you able to repro this on other Android Studio and/or IntelliJ versions on your Linux machine?

**Comment by sindrenm** [comment]
Yeah, reproducible on both Bumblebee Canary 1 and Android Studio 4.2.1. When I first launched it on 4.2.1, however, it didn't crash, but it also just opened a black window with no content and completely froze the IDE. Had to force-close the process, after which when I tried again on a new instance, the same crashes occurred.

**Comment by c5inco** [comment]
Gotcha - good to know. Are you able to repro the crash also in IntelliJ 2020.3 or 2021.1? Would really appreciate if you can confirm this. Trying to diagnose if it's Compose Desktop or IntelliJ platform issue.

**Comment by sindrenm** [comment]
Crashes in IDEA 2021.1.1 as well. Ran through Flatpak, though, as that's how I've installed it on my system, but here's the crash dump:

```
free(): invalid pointer
/app/idea-IC/bin/idea.sh: line 182:    18 Aborted                 (core dumped) "$JAVA_BIN" -classpath "$CLASSPATH" ${VM_OPTIONS} "-XX:ErrorFile=$HOME/java_error_in_idea_%p.log" "-XX:HeapDumpPath=$HOME/java_error_in_idea_.hprof" "-Didea.vendor.name=${PRODUCT_VENDOR}" "-Didea.paths.selector=${PATHS_SELECTOR}" "-Djb.vmOptionsFile=${USER_VM_OPTIONS_FILE:-${VM_OPTIONS_FILE}}" ${IDE_PROPERTIES_PROPERTY} -Didea.platform.prefix=Idea -Didea.jre.check=true com.intellij.idea.Main "$@"
```

I don't see anything useful in there, but maybe you do.

**Comment by c5inco** [comment]
Thanks for the confirmation! Seems it is related to this Compose Desktop [issue](https://github.com/JetBrains/compose-jb/issues/416) with the Skiko dependency. I'm working on upgrading to 0.4.0 from 0.3.0, so hopefully it will just work with the upgrade.

**Comment by sindrenm** [comment]
Thanks! Feel free to ping me here when you've upgraded if you want me to test further. :clap:

**Comment by c5inco** [comment]
I just updated the plugin to 0.1.8 which uses Compose Desktop 0.4.0, so let me know if that fixes things for you!

**Comment by sindrenm** [comment]
Version 0.1.8 works perfectly fine in IDEA! Thanks a ton for the update. Feel free to close this issue. :slightly_smiling_face:
