### ISSUE TITLE
Plugin is not compatible with IU-212.* version

### ISSUE THREAD

**Issue by sureshg** [c5inco/Compose-Modifiers-Playground#4]
Plugin error: Plugin `Compose Modifiers Playground` (version '0.1.7') is not compatible with the current version of the IDE, because it requires build `211.*` or older but the current build is `IU-212.5080.55`

**Comment by c5inco** [comment]
Thank you for reporting - updating the version support now!

**Comment by c5inco** [comment]
v0.1.9 is out and should work with IntelliJ 212.*

**Comment by sureshg** [comment]
@c5inco  could you update for 2021.3 also?

**Comment by c5inco** [comment]
Yep doing it now! The ole version bump. I wish plugins would just support a wild card character so that it always opportunistically supports the newest version. 😅

**Comment by c5inco** [comment]
New version up and running!
