### ISSUE TITLE
GUI freezes when trying to scroll with the mouse pointer

### ISSUE THREAD

**Issue by mipastgt** [c5inco/Compose-Modifiers-Playground#8]
GUI freezes when trying to scroll with the mouse pointer. Scrolling via mouse-wheel works but not if you try to click on the scroll bar the right and move it. After that attempt the GUI is frozen. Tried this on Firefox and Chrome.

**Comment by c5inco** [comment]
Thanks for the report! This should be fixed with commit [c8ca1ef](https://github.com/c5inco/Compose-Modifiers-Playground/commit/c8ca1efac71bb13197a8a2c3fd63e5d1126abd54) with the update to Compose 1.5.1.
